<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseurl = $storeManager->getStore()->getBaseUrl();
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 
?>
<div class="content-header">
	<table cellspacing="0">
		<tbody>
			<tr>
				<td style="width: 50%;"><h3 class="icon-head head-upcoming"><?php echo __('Export Attributes'); ?></h3></td>
				<td class="a-right">&nbsp;</td>
			</tr>
		</tbody>
	</table>
</div>
<div class="entry-edit">
	<form method="post" action="<?php echo $block->getPostUrl(); ?>" id="edit_form">
		<div><input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey()  ?>" /></div>
		<fieldset class="fieldset admin__fieldset " id="base_fieldset">
		<div class="messages"></div>
		<div class="admin__field field field-entity " data-ui-id="export-form-container-form-fieldset-element-form-field-entity">
			<label class="label admin__field-label" for="entity" data-ui-id="export-form-container-form-fieldset-element-select-entity-label"><span><?php echo __('Entity Type'); ?></span></label>
			<div class="admin__field-control control">
				<select id="entity" name="entity" title="Entity Type" onchange="varienExport.getFilter();" class=" select admin__control-select" data-ui-id="export-form-container-form-fieldset-element-select-entity">
				<option value="catalog_attribute"><?php echo __('Attributes'); ?></option>
				</select>
			</div>
		</div>
		<div class="admin__field field field-file_format " data-ui-id="export-form-container-form-fieldset-element-form-field-file-format">
			<label class="label admin__field-label" for="file_format" data-ui-id="export-form-container-form-fieldset-element-select-file-format-label"><span><?php echo __('Export File Format'); ?></span></label>
			<div class="admin__field-control control">
				<select id="file_format" name="file_format" title="Export File Format" class=" select admin__control-select" data-ui-id="export-form-container-form-fieldset-element-select-file-format">
				<option value="csv">CSV</option>
				</select>
			</div>
		</div>
		<div class="admin__field field field-file_format " data-ui-id="export-form-container-form-fieldset-element-form-field-file-format">
			<label class="label admin__field-label" for="file_format" data-ui-id="export-form-container-form-fieldset-element-select-file-format-label"><span></span></label>
			<div class="admin__field-control control">
					<button type="submit" class="button"><?php echo __('Submit'); ?></button> 
			</div>
		</div>
		</fieldset>
	</form>
</div>


<div class="content-header">
	<table cellspacing="0">
		<tbody>
			<tr>
				<td style="width: 50%;"><h3 class="icon-head head-upcoming"><?php echo __('Import Attributes'); ?></h3></td>
				<td class="a-right">&nbsp;</td>
			</tr>
		</tbody>
	</table>
</div>


<div class="entry-edit">
	<form enctype="multipart/form-data" method="post" action="<?php echo $block->getImportUrl('category', 'categories'); ?>" id="edit_form">
	<div><input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey() ?>" /></div>
		<fieldset class="fieldset admin__fieldset " id="base_fieldset">
	
		<div class="messages"></div>
		<div class="admin__field field field-entity " data-ui-id="export-form-container-form-fieldset-element-form-field-entity">
			<label class="label admin__field-label" for="entity" data-ui-id="export-form-container-form-fieldset-element-select-entity-label"><span><?php echo __('Entity Type'); ?></span></label>
			<div class="admin__field-control control">
				<select id="entity" name="entity" title="Entity Type" onchange="varienExport.getFilter();" class=" select admin__control-select" data-ui-id="export-form-container-form-fieldset-element-select-entity">
				<option value="catalog_attribute"><?php echo __('Attributes'); ?></option>
				</select>
			</div>
		</div>
		<div class="admin__field field field-file_format " data-ui-id="export-form-container-form-fieldset-element-form-field-file-format">
			<label class="label admin__field-label" for="file_format" data-ui-id="export-form-container-form-fieldset-element-select-file-format-label"><span><?php echo __('Select File to import'); ?></span></label>
			<div class="admin__field-control control">
				<input type="file" class=" required-entry" title="Select File to Import" value="" name="import_fileatt" id="import_file">
			</div>
		</div>
		<div class="admin__field field field-file_format " data-ui-id="export-form-container-form-fieldset-element-form-field-file-format">
		<label class="label admin__field-label" for="file_format" data-ui-id="export-form-container-form-fieldset-element-select-file-format-label"><span></span></label>
		<div class="admin__field-control control">
			<a href="<?php echo $block->getBaseUrl(); ?>ds_attribute/sample_import_attribute.csv">Please find attached sample CSV file to import</a>
			</div>
		</div>

		<div class="admin__field field field-file_format " data-ui-id="export-form-container-form-fieldset-element-form-field-file-format">
			<label class="label admin__field-label" for="file_format" data-ui-id="export-form-container-form-fieldset-element-select-file-format-label"><span></span></label>
			<div class="admin__field-control control">
					<button type="submit" class="button"><?php echo __('Submit'); ?></button> 
			</div>
		</div>
	
		</fieldset>
	</form>
</div>
